### ISSUE TITLE
Reference footnote in text and list of all references at the end of page

### ISSUE THREAD

**Issue by nicolashimmelmann** [winkm89/teachPress#192]
Hi Michael,

first of all, thanks a lot for your great plugin! Up to now it's the best one I have found for managing references with WordPress.

Is there any way to add references inline in the text (like a footnote), and having a list of all references cited on the page at the bottom? I could not find a way how to do this. Ideally, when clicking the footnote the page would jump to the correct reference in the reference section at the end. 

Looking forward to your answer.

Cheers,
Nicolas

**Comment by nicolashimmelmann** [comment]
Yes, that is exactly what I was looking for. What a nice coincidence that you already implemented this feature! Thanks for extending the docs about it, I think there will be more people happy about this :)

**Comment by nicolashimmelmann** [comment]
Maybe a quick hint, just so you know:
When I add `[tpref show_links="1"]` without any tpcite, I get an exception in the editor and can't edit the post anymore. I need to remove the tpref from the post in the database and then I can edit again. I get the following exception:

```
Fatal error: Uncaught Error: Call to a member function get_ref() on null in /www/wp/wp-content/plugins/teachpress/core/shortcodes.php:980 
Stack trace: 
#0 /www/wp/wp-includes/shortcodes.php(356): tp_ref_shortcode(Array, '', 'tpref') 
#1 [internal function]: do_shortcode_tag(Array) 
#2 /www/wp/wp-includes/shortcodes.php(228): preg_replace_callback('/\\[(\\[?)(tpref)...', 'do_shortcode_ta...', '\r\n<p>...') 
#3 /www/wp/wp-includes/class-wp-hook.php(307): do_shortcode('\r\n<p>...') 
#4 /www/wp/wp-includes/plugin.php(189): WP_Hook->apply_filters('\r\n<p>...', Array) 
#5 /www/wp/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(1811): apply_filters('the_content', '<!-- wp:paragra...')
#6 /www/wp/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php(560): WP_REST_Posts_Controller->prepare_item_for_response(Object(WP_Post), Object(WP_REST_Request))
#7 /www/wp/wp-includes/rest-api/class-wp-rest-server.php(1141): WP_REST_Posts_Controller->get_item(Object(WP_REST_Request))
#8 /www/wp/wp-includes/rest-api/class-wp-rest-server.php(988): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wp/v2/posts/(?...', Array, NULL)
#9 /www/wp/wp-includes/rest-api.php(511): WP_REST_Server->dispatch(Object(WP_REST_Request))
#10 /www/wp/wp-includes/rest-api.php(2860): rest_do_request(Object(WP_REST_Request))
#11 [internal function]: rest_preload_api_request(Array, '/wp/v2/posts/35...')
#12 /www/wp/wp-includes/block-editor.php(492): array_reduce(Array, 'rest_preload_ap...', Array)
#13 /www/wp/wp-admin/edit-form-blocks.php(72): block_editor_rest_api_preload(Array, Object(WP_Block_Editor_Context))
#14 /www/wp/wp-admin/post.php(187): require('/users/...')
#15 {main} thrown in /www/wp/wp-content/plugins/teachpress/core/shortcodes.php on line 980
```
